// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7aL7kEQHJ6s4m35YB7-732j_a-pv9Yc',
    appId: '1:240851646568:web:d262c29ea8a813b7bbe3dd',
    messagingSenderId: '240851646568',
    projectId: 'protibeshi-bazar',
    authDomain: 'protibeshi-bazar.firebaseapp.com',
    storageBucket: 'protibeshi-bazar.appspot.com',
    measurementId: 'G-TLP8YXH150',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD47dvFC9t31Iwj6KCHnshBKAxjttlG06E',
    appId: '1:240851646568:android:06c51c9ceea5d7c6bbe3dd',
    messagingSenderId: '240851646568',
    projectId: 'protibeshi-bazar',
    storageBucket: 'protibeshi-bazar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUGWstJacdDf5mcB0eEwRL0GB-cjtDsDI',
    appId: '1:240851646568:ios:1bf80226d5d1548dbbe3dd',
    messagingSenderId: '240851646568',
    projectId: 'protibeshi-bazar',
    storageBucket: 'protibeshi-bazar.appspot.com',
    iosBundleId: 'com.example.prac2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUGWstJacdDf5mcB0eEwRL0GB-cjtDsDI',
    appId: '1:240851646568:ios:965454fd1550ce50bbe3dd',
    messagingSenderId: '240851646568',
    projectId: 'protibeshi-bazar',
    storageBucket: 'protibeshi-bazar.appspot.com',
    iosBundleId: 'com.example.prac2.RunnerTests',
  );
}
